# Generated by Django 3.2.23 on 2023-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='excercies',
            new_name='equipment',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.TextField(blank=True, null=True),
        ),
    ]
