# Generated by Django 3.2.23 on 2023-12-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_image_recipe_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
    ]
