# Generated by Django 3.2.23 on 2023-12-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20231212_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='otherpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='status',
        ),
    ]
