# Generated by Django 3.2.23 on 2023-11-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guides',
            new_name='Guide',
        ),
    ]
