# Generated by Django 3.2.23 on 2023-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_guides_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='type_of_guide',
            field=models.CharField(choices=[('Digital Copy', 'Digital Copy'), ('Physical Copy', 'Physical Copy'), ('Both Digital and Physical Copy', 'Both Digital and Physical Copy')], max_length=50),
        ),
    ]
